package com.eeseka.lynk.shared.design_system.theme

import androidx.compose.material3.darkColorScheme as materialDarkColorScheme
import androidx.compose.material3.lightColorScheme as materialLightColorScheme
import com.slapps.cupertino.theme.darkColorScheme as cupertinoDarkColorScheme
import com.slapps.cupertino.theme.lightColorScheme as cupertinoLightColorScheme

val MaterialLightScheme = materialLightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight
)

val MaterialDarkScheme = materialDarkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark
)

val CupertinoLightScheme = cupertinoLightColorScheme(
    accent = primaryLight,
    systemBackground = backgroundLight,
    secondarySystemBackground = surfaceContainerLowLight,
    tertiarySystemBackground = surfaceVariantLight,
    label = onBackgroundLight,
    secondaryLabel = onSurfaceVariantLight,
    tertiaryLabel = outlineVariantLight,
    quaternaryLabel = outlineVariantLight.copy(alpha = 0.5f),
    systemFill = surfaceVariantLight,
    secondarySystemFill = surfaceContainerHighestLight,
    tertiarySystemFill = surfaceContainerHighLight,
    quaternarySystemFill = surfaceContainerLight,
    placeholderText = onSurfaceVariantLight,
    separator = outlineVariantLight,
    opaqueSeparator = outlineVariantLight,
    link = primaryLight,
    systemGroupedBackground = surfaceContainerLowestLight,
    secondarySystemGroupedBackground = surfaceLight,
    tertiarySystemGroupedBackground = surfaceVariantLight
)

val CupertinoDarkScheme = cupertinoDarkColorScheme(
    accent = primaryDark,
    systemBackground = backgroundDark,
    secondarySystemBackground = surfaceContainerLowDark,
    tertiarySystemBackground = surfaceVariantDark,
    label = onBackgroundDark,
    secondaryLabel = onSurfaceVariantDark,
    tertiaryLabel = outlineVariantDark,
    quaternaryLabel = outlineVariantDark.copy(alpha = 0.5f),
    systemFill = surfaceVariantDark,
    secondarySystemFill = surfaceContainerHighestDark,
    tertiarySystemFill = surfaceContainerHighDark,
    quaternarySystemFill = surfaceContainerDark,
    placeholderText = onSurfaceVariantDark,
    separator = outlineVariantDark,
    opaqueSeparator = outlineVariantDark,
    link = primaryDark,
    systemGroupedBackground = surfaceContainerLowestDark,
    secondarySystemGroupedBackground = surfaceDark,
    tertiarySystemGroupedBackground = surfaceVariantDark
)